from pathlib import Path
import hashlib,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.')
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def apply_ops(path,expected_base,expected_final,ops):
    assert sha(path)==expected_base,(path,sha(path),expected_base)
    lines=path.read_text(encoding='utf-8-sig').splitlines(keepends=True)
    out=[];pos=0
    for op in ops:
        kind,i1,i2=op[:3]; out.extend(lines[pos:i1])
        if kind=='normal': out.append(op[3])
        else:
            old_mid,new_mid,line_hash,prefix_len,suffix_len=op[3],op[4],op[5],op[6],op[7]
            line=lines[i1]; ending='\n' if line.endswith('\n') else ''
            raw=line[:-1] if ending else line
            if raw.endswith('\r'): raw=raw[:-1]; ending='\r\n'
            assert hashlib.sha256(raw.encode()).hexdigest()==line_hash
            assert raw[prefix_len:len(raw)-suffix_len if suffix_len else len(raw)]==old_mid,(path,'middle mismatch')
            out.append(raw[:prefix_len]+new_mid+(raw[len(raw)-suffix_len:] if suffix_len else '')+ending)
        pos=i2
    out.extend(lines[pos:])
    path.write_text(''.join(out),encoding='utf-8')
    assert sha(path)==expected_final,(path,sha(path),expected_final)
BASE={'index.html':'de3cc2c8874d701c5c3122dbad9e9625fd9fc70249dceb1089abbc3a9ca45973','manifest.json':'87f5c165b411ff72f3ddcaaaea16b78418b7d23eb2ee2736e6b2f129a38653a4','sw.js':'5fd106452e8f133f484eb2959453e6254ea9eb99cec2f9af60bce64b526b5e5b','version.json':'82554ec4c1b9f90a6c97fc7334cb90ca40eb066049764bbabef42178c7c4259f'}
FINAL={'index.html':'1eca57561fe56a57592b7bc5ddff7da8eae7ef64aec9bdeb83566c7549881fa4','manifest.json':'0f35ac2cd3155a60bb86b30f6dd3c2977058c383d545ffdd7a7df48b10596828','sw.js':'d5ce70a00977174c9832f8aa58192659e8411e584777f764a468c0b8fd3862fb','version.json':'4f56f4b884358022a7e822976ce35b703fa6bcd3f33117b8a55a356a936d6391'}
OPS={'index.html':[
('normal',4,5,'<meta http-equiv="Content-Security-Policy" content="default-src \'self\'; script-src \'self\' \'unsafe-inline\'; script-src-elem \'sha256-s9m69q3HVZeROoD1XSN5Kk4j7UxPh201ux4HNHwh77c=\'; script-src-attr \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'; style-src-elem \'sha256-TCcbfO+mypkqr4u/EOawkzX3FN85O8c+8DZgmqRA+K0=\' \'sha256-FNrlLu4Fxj1b29d7a1Dnil2AJ4le7xprL9Ez1KEF+UQ=\' \'sha256-/PDid79K7LRUFTBYGYCk5WowaPjSf8h6n32Q2Qfk09Y=\'; style-src-attr \'unsafe-inline\'; font-src \'self\' data:; img-src \'self\' data:; connect-src \'self\'; manifest-src \'self\'; worker-src \'self\'; media-src \'none\'; base-uri \'none\'; form-action \'none\'; object-src \'none\'; frame-src \'none\'">\n'),
('normal',51,51,'\n/* v117 pre-physical Wave-2 closure — F-01 + F-30.\n   Desktop navigation participates in the app flex column instead of covering reader text.\n   Mobile/tablet <=768 keeps the established fixed bottom navigation. */\n@media (min-width: 769px) {\n  .bottom-nav {\n    position: relative !important; bottom: auto !important; left: auto !important; right: auto !important;\n    transform: none !important; width: 100% !important; max-width: none !important; flex: 0 0 auto !important;\n    border-left: 0 !important; border-right: 0 !important; border-bottom: 0 !important; border-radius: 0 !important;\n  }\n  #content { padding-bottom: calc(2rem + env(safe-area-inset-bottom, 0px)) !important; }\n}\n/* F-30: retain visible control boundaries when system forced-colors removes fill distinctions. */\n@media (forced-colors: active) {\n  .bn-item, .mark-btn, .mark-read-btn, .onboarding-primary, .theme-pref-btn,\n  .library-title-mark-btn, .library-quick-chip, .hour-end-btn, .cc-primary,\n  .resume-panel-btn.primary, .note-save-btn, .sf-btn.active {\n    border: 1px solid ButtonText !important;\n    forced-color-adjust: auto;\n  }\n}\n'),
('normal',483,483,'/* v116 F-04 — dark-theme accent-filled controls use dark ink on gold. */\n[data-theme="dark"] .mark-btn:not(.done),\n[data-theme="dark"] .theme-pref-btn.active,\n[data-theme="dark"] .library-title-mark-btn[aria-pressed="true"],\n[data-theme="dark"] .library-quick-chip.active,\n[data-theme="dark"] .hour-end-btn.primary,\n[data-theme="dark"] .cc-primary,\n[data-theme="dark"] .resume-panel-btn.primary,\n[data-theme="dark"] .note-save-btn,\n[data-theme="dark"] .update-banner,\n[data-theme="dark"] .update-refresh-btn,\n[data-theme="dark"] .help-round:hover,\n[data-theme="dark"] .help-round:focus-visible,\n[data-theme="dark"] .panel-close-btn:hover,\n[data-theme="dark"] .panel-close-btn:focus-visible { color: var(--bg); }\n'),
('normal',921,922,'.mark-btn:focus-visible { outline: 3px solid var(--focus-ring); outline-offset: 2px; }\n'),
('normal',3290,3291,'  <textarea class="note-textarea" id="noteTextarea" aria-label="Note personnelle" placeholder="Ajouter une note…" maxlength="2000" oninput="updateNoteCharCount()"></textarea>\n'),
('normal',5710,5711,"const APP_VERSION = 'v119';\n"),
('normal',5712,5715,"const APP_EVIDENCE_STAGE = '24H_V119_FINAL_PREPHYSICAL_B1';\nconst APP_RELEASE_SEQUENCE = 119000001;\nconst APP_RELEASE_ID = '24h-v119-b1-20260930-prephysical';\n"),
('normal',5924,5927,"    for (const p of h.paragraphs || []) if (p.id === paraId) return {id:paraId, text:p.t, type:'hour_meditation', label:`${ordinalHeure(h.hour_number)} — ${h.title}`, hourNum:h.hour_number, openType:'meditation'};\n    for (const p of h.reflections || []) if (p.id === paraId) return {id:paraId, text:p.t, type:'hour_reflection', label:`${ordinalHeure(h.hour_number)} — Réflexions`, hourNum:h.hour_number, openType:'reflection'};\n    for (const sub of h.subsections || []) for (const p of sub.paragraphs || []) if (p.id === paraId) return {id:paraId, text:p.t, type:'hour_subsection', label:`${ordinalHeure(h.hour_number)} — ${sub.title || h.title}`, hourNum:h.hour_number, openType:'subsection'};\n"),
('huge',6254,6255,'','r','d1adca4231bd6c08e3f6ecde0d7dac5d1b4550a96d3912ca494ebfe129c23cb7',96476,453864),
('normal',8092,8093,'    <div class="resume-panel-title">${ordinalHeure(h.hour_number)} — ${escHtml(h.title)}</div>\n'),
('normal',8185,8185,'  cancelPendingSelectionCapture();\n'),
('normal',8293,8294,'        onclick="openHour(${h.hour_number})" title="${escHtml(h.title)} — ${h.display_time}${[5,6,7].includes(h.hour_number)?\' · Heure Sainte\':\'\'}" aria-label="Ouvrir la ${ordinalHeure(h.hour_number)} : ${escHtml(h.title)} — ${h.display_time}">\n'),
('normal',8300,8301,'      onclick="openHour(${h.hour_number})" aria-label="Ouvrir la ${ordinalHeure(h.hour_number)} : ${escHtml(h.title)} — ${h.display_time}">\n'),
('normal',8594,8595,'    ${lastH ? `<button type="button" class="espace-resume-hero" onclick="openHour(${lastH.hour_number}, true, { resume: true })"><div class="erh-inner"><div class="erh-label">Reprendre</div><div class="erh-title">${ordinalHeure(lastH.hour_number)} — ${escHtml(lastH.title)}</div><div class="erh-meta">${escHtml(describeSavedPara(getSavedParaForHour(lastH.hour_number)))} · ${escHtml(lastH.display_time)}</div></div><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="flex-shrink:0;color:var(--accent)"><polyline points="9 18 15 12 9 6"/></svg></button>` : \'\'}\n'),
('normal',8630,8631,"  const primaryDesc = lastH ? `${ordinalHeure(lastH.hour_number)} · ${escHtml(describeSavedPara(getSavedParaForHour(lastH.hour_number)))} · ${lastH.display_time}` : 'Entrer dans les 24 Heures de la Passion, une Heure à la fois.';\n"),
('normal',8806,8808,'    <div class="tabs" role="tablist" aria-label="Sections de l’Heure">\n      <button class="tab-btn ${state.activeTab===\'meditation\'?\'active\':\'\'}" role="tab" id="readerTabMeditation" aria-selected="${state.activeTab===\'meditation\'?\'true\':\'false\'}" aria-controls="meditationContent" tabindex="${state.activeTab===\'meditation\'?\'0\':\'-1\'}" data-tab="meditation" onclick="switchTab(\'meditation\')" onkeydown="handleReaderTabKeydown(event)">\n'),
('normal',8810,8811,'      ${hasRefl ? `<button class="tab-btn ${state.activeTab===\'reflections\'?\'active\':\'\'}" role="tab" id="readerTabReflections" aria-selected="${state.activeTab===\'reflections\'?\'true\':\'false\'}" aria-controls="reflectionsContent" tabindex="${state.activeTab===\'reflections\'?\'0\':\'-1\'}" data-tab="reflections" onclick="switchTab(\'reflections\')" onkeydown="handleReaderTabKeydown(event)">\n'),
('normal',8813,8814,'      <button class="tab-btn ${state.activeTab===\'linked\'?\'active\':\'\'}" role="tab" id="readerTabLinked" aria-selected="${state.activeTab===\'linked\'?\'true\':\'false\'}" aria-controls="linkedTextsContent" tabindex="${state.activeTab===\'linked\'?\'0\':\'-1\'}" data-tab="linked" onclick="switchTab(\'linked\')" onkeydown="handleReaderTabKeydown(event)">\n'),
('normal',8854,8855,'    <div id="meditationContent" role="tabpanel" aria-labelledby="readerTabMeditation" aria-hidden="${!hasRefl||state.activeTab===\'meditation\'?\'false\':\'true\'}" style="display:${!hasRefl||state.activeTab===\'meditation\'?\'block\':\'none\'}">\n'),
('normal',8857,8858,'    <div id="reflectionsContent" role="tabpanel" aria-labelledby="readerTabReflections" aria-hidden="${hasRefl&&state.activeTab===\'reflections\'?\'false\':\'true\'}" style="display:${hasRefl&&state.activeTab===\'reflections\'?\'block\':\'none\'}">\n'),
('normal',8860,8861,'    <div id="linkedTextsContent" role="tabpanel" aria-labelledby="readerTabLinked" aria-hidden="${state.activeTab===\'linked\'?\'false\':\'true\'}" style="display:${state.activeTab===\'linked\'?\'block\':\'none\'}">\n'),
('normal',9258,9258,"function handleReaderTabKeydown(event) {\n  const key = event && event.key;\n  if (!['ArrowLeft','ArrowRight','Home','End'].includes(key)) return;\n  const tabs = Array.from(document.querySelectorAll('.tabs [role="tab"]'));\n  if (!tabs.length) return;\n  const current = event.currentTarget;\n  let index = Math.max(0, tabs.indexOf(current));\n  if (key === 'ArrowLeft') index = (index - 1 + tabs.length) % tabs.length;\n  else if (key === 'ArrowRight') index = (index + 1) % tabs.length;\n  else if (key === 'Home') index = 0;\n  else if (key === 'End') index = tabs.length - 1;\n  event.preventDefault();\n  const next = tabs[index];\n  next.focus();\n  switchTab(next.dataset.tab);\n}\n\n"),
('normal',9265,9268,"  if (med) { const on = tab === 'meditation'; med.style.display = on ? 'block' : 'none'; med.setAttribute('aria-hidden', on ? 'false' : 'true'); }\n  if (ref) { const on = tab === 'reflections'; ref.style.display = on ? 'block' : 'none'; ref.setAttribute('aria-hidden', on ? 'false' : 'true'); }\n  if (linked) { const on = tab === 'linked'; linked.style.display = on ? 'block' : 'none'; linked.setAttribute('aria-hidden', on ? 'false' : 'true'); }\n"),
('normal',9269,9270,"    const on = btn.dataset.tab === tab;\n    btn.classList.toggle('active', on);\n    btn.setAttribute('aria-selected', on ? 'true' : 'false');\n    btn.tabIndex = on ? 0 : -1;\n"),
('normal',10162,10163,'    <div class="right-context-card"><div class="right-context-title">Reprendre</div><div class="right-context-meta">${h ? `${ordinalHeure(h.hour_number)} — ${escHtml(h.title)}<br>${escHtml(describeSavedPara(getSavedParaForHour(h.hour_number)))}` : \'Aucune position enregistrée.\'}</div>${h ? `<button type="button" class="resume-panel-btn primary" onclick="openHour(${h.hour_number}, true, { resume: true })">Reprendre</button> <button type="button" class="resume-panel-btn" onclick="openHour(${h.hour_number})">Ouvrir au début</button>` : \'\'}</div>\n'),
('normal',10407,10408,'    const label=(labelBase||`${ordinalHeure(hour.hour_number)} — ${hour.title}`);\n'),
('normal',10502,10503,"      const u=searchNewUnit(searchBaseMeta('hour','hour',`${ordinalHeure(hour.hour_number)} — ${hour.title}`,'Heure',{kind:'hour',n:hour.hour_number,paraId:first.id,tab:'meditation'},'HOUR:'+hour.hour_number,'title'));\n"),
('normal',10508,10509,"        const u=searchNewUnit(searchBaseMeta('hour','hour',`${ordinalHeure(hour.hour_number)} — ${sub.title}`,'Heure',{kind:'hour',n:hour.hour_number,paraId:sub.paragraphs[0].id,tab:'meditation'},'HOUR:'+hour.hour_number,'title'));\n"),
('normal',10511,10512,'      searchPushUnits(normal,searchBuildMeditationUnits(hour,sub.paragraphs||[],`${ordinalHeure(hour.hour_number)} — ${sub.title||hour.title}`));\n'),
('normal',10514,10515,"      const meta=searchBaseMeta('reflection','reflection',`${ordinalHeure(hour.hour_number)} — ${hour.title}`,'Réflexion',{kind:'hour',n:hour.hour_number,paraId:p.id,tab:'reflection'},'REFLECTION:'+hour.hour_number,'body');\n"),
('normal',11785,11786,"  const captureGeneration = _selectionCaptureGeneration;\n  if (_selectionFinalizeTimer) clearTimeout(_selectionFinalizeTimer);\n  _selectionFinalizeTimer = setTimeout(function () {\n    _selectionFinalizeTimer = null;\n    if (captureGeneration !== _selectionCaptureGeneration || state.view === 'home') return;\n"),
('normal',13537,13537,'let _selectionFinalizeTimer = null;\nlet _selectionCaptureGeneration = 0;\nfunction cancelPendingSelectionCapture() {\n  _selectionCaptureGeneration += 1;\n  if (_selectionCaptureTimer) { clearTimeout(_selectionCaptureTimer); _selectionCaptureTimer = null; }\n  if (_selectionFinalizeTimer) { clearTimeout(_selectionFinalizeTimer); _selectionFinalizeTimer = null; }\n}\n'),
('normal',13541,13541,'    _selectionCaptureTimer = null;\n')
],
'manifest.json':[('normal',41,42,'  "version": "v119",\n'),('normal',43,45,'  "release_sequence": 119000001,\n  "release_id": "24h-v119-b1-20260930-prephysical"\n')],
'sw.js':[('normal',0,1,'/* v119 B1 — pre-physical successor: v115 race closure + Wave-1 accessibility + bounded F-01/F-09/F-30 Wave-2 repairs; protected corpus/Search ranking/personal-state/backup semantics preserved */\n'),('normal',7,8,"const APP_VERSION = 'v119';\n"),('normal',9,11,"const RELEASE_SEQUENCE = 119000001;\nconst RELEASE_ID = '24h-v119-b1-20260930-prephysical';\n"),('normal',12,13,"const CANONICAL_SHELL_SHA256 = '1eca57561fe56a57592b7bc5ddff7da8eae7ef64aec9bdeb83566c7549881fa4';\n"),('normal',15,16,'const CACHE_NAME = `${CACHE_PREFIX}v119-b1`;\n')],
'version.json':[
('normal',1,2,'  "app_version": "v119",\n'),('normal',3,4,'  "cache_name": "scope-derived:luisa-24h-<scope-fingerprint>-v119-b1",\n'),
('normal',9,12,'  "release_scope": "v119/B1 release-integrity successor of exact v118/B1: corrects active pre-physical gate targets and the shell evidence-stage identity so every current operational reference names the exact v119 candidate. All v118 functional repairs are preserved; no corpus paragraph, Search ranking, personal-state schema, backup semantics, provenance decision or stable identifier is changed.",\n  "real_device_status": "V119_B1_FINAL_PREPHYSICAL_CANDIDATE__MACHINE_AND_APP_TEST_QUALIFICATION_REQUIRED__INSTALLED_PWA_OFFLINE_IPHONE_IPAD_GATES_OPEN",\n  "overall_release_status": "V119_B1_FINAL_PREPHYSICAL_CANDIDATE__PRODUCTION_NOT_AUTHORIZED",\n'),
('normal',13,16,'    "Exact production v111/R36 → v119/B1 installed-PWA update/activation and acknowledged-state preservation on iPhone and iPad.",\n    "v119/B1 iPad H03/P013 physical A–D replay of the inherited native-selection surface: direct P013 selection; highlight/persistence; P012→P013 regression; selection inside existing cross-record highlight.",\n    "v119/B1 provenance panels for normal Hours and H08/H23/H24, plus methodology and Help, at Très grand in portrait and landscape.",\n'),
('normal',26,29,'    "Exact production v111/R36 → v119/B1 installed-PWA update/activation and acknowledged-state preservation on iPhone and iPad.",\n    "v119/B1 iPad H03/P013 physical A–D replay of the inherited native-selection surface: direct P013 selection; highlight/persistence; P012→P013 regression; selection inside existing cross-record highlight.",\n    "v119/B1 provenance panels for normal Hours and H08/H23/H24, plus methodology and Help, at Très grand in portrait and landscape.",\n'),
('normal',41,42,'  "postfreeze_reopen_evidence": "Final staleness scan of v118 found active physical-gate metadata still targeting v117 and APP_EVIDENCE_STAGE still naming v116. v119 corrects those release-integrity identities plus mandatory version/CSP/cache/hash bindings; application behavior is otherwise preserved.",\n'),
('normal',56,58,'  "release_sequence": 119000001,\n  "release_id": "24h-v119-b1-20260930-prephysical",\n'),('normal',59,60,'  "canonical_shell_sha256": "1eca57561fe56a57592b7bc5ddff7da8eae7ef64aec9bdeb83566c7549881fa4",\n'),
('normal',79,81,'  "functional_freeze_status": "V119_B1_FINAL_PREPHYSICAL__V118_FUNCTIONAL_BYTES_PRESERVED_EXCEPT_MECHANICAL_IDENTITY__ACTIVE_GATE_TARGETS_CORRECTED__PROTECTED_SURFACES_UNCHANGED",\n  "security_stage_status": "CSP3_ARCHITECTURE_PRESERVED__V119_INLINE_SCRIPT_AND_STYLE_HASHES_REBOUND_TO_EXACT_V119_SHELL__SW_CACHE_AND_CANONICAL_SHELL_HASH_BOUND_TO_EXACT_V119_BYTES",\n'),
('normal',84,85,'  "security_inline_script_sha256_base64": "sha256-s9m69q3HVZeROoD1XSN5Kk4j7UxPh201ux4HNHwh77c=",\n'),('normal',86,88,'    "sha256-TCcbfO+mypkqr4u/EOawkzX3FN85O8c+8DZgmqRA+K0=",\n    "sha256-FNrlLu4Fxj1b29d7a1Dnil2AJ4le7xprL9Ez1KEF+UQ=",\n'),
('normal',693,694,'    "qualification_status": "SUPERSEDED__ADVERSARIAL_FAIL__24H-SEL-NAV-02_AND_STALE_ACTIVE_METADATA"\n  },\n  "v116_b1_prephysical": {\n    "predecessor_version": "v115/B1",\n    "predecessor_zip_sha256": "76177603e4c9f6e9df17bd8f1f82def48601b760d3010ec478fd3dc9c8ac5001",\n    "scope": [\n      "24H-SEL-NAV-02",\n      "F-03",\n      "F-04",\n      "F-07",\n      "F-28",\n      "mechanical v116 identity/CSP/cache/hash rebinding"\n    ],\n    "selection_repair": "Track/cancel both selection-capture and delayed selection-finalization timers; generation invalidation plus Home-view guard prevents post-Home resurrection of pending contextual state.",\n    "accessibility_repairs": [\n      "Recovery meditation action uses the governed focus-ring token",\n      "Dark-theme accent-filled interactive states use dark ink on gold",\n      "Reader tabs implement tablist/tab/tabpanel selected state and Arrow/Home/End keyboard operation",\n      "Note textarea has a durable accessible name"\n    ],\n    "protected_surfaces": [\n      "CORPUS",\n      "TEXT_LIBRARY",\n      "SPEECH_DATA",\n      "PROVENANCE_PUBLIC_PROJECTION",\n      "Search semantics",\n      "personal-state schema",\n      "IndexedDB/Web-Locks concurrency architecture",\n      "Wave-0 backup/import semantics",\n      "Update-v2 protocol"\n    ],\n    "production_deployment_authority": "NONE",\n    "qualification_status": "CANDIDATE_BUILT__FRESH_MACHINE_AND_ADVERSARIAL_QUALIFICATION_REQUIRED"\n  },\n  "v119_b1_final_prephysical": {\n    "predecessor": "v118/B1",\n    "predecessor_zip_sha256": "354c5f69ccadc0a4c07e920f79703083d37df8ef4620b479a645125e29071ace",\n    "finding": "release-integrity staleness in active gate/evidence-stage identity",\n    "authorized_scope": [\n      "advance active physical-gate targets v117/B1 -> v119/B1",\n      "advance APP_EVIDENCE_STAGE to v119 final-prephysical",\n      "mechanical version/release/CSP/cache/canonical-shell bindings"\n    ],\n    "functional_behavior_mutation": "NONE",\n    "protected_surface_mutation": "NONE",\n    "production_authorized": false\n'),
('normal',695,696,'')
]}
for fn in ['index.html','luisa_24_heures.html']:
    apply_ops(root/fn,BASE['index.html'],FINAL['index.html'],OPS['index.html'])
for fn in ['manifest.json','sw.js','version.json']:
    apply_ops(root/fn,BASE[fn],FINAL[fn],OPS[fn])
print('24H_V119_EXACT_OK')
