#!/usr/bin/env python3
from pathlib import Path
import sys,zipfile,hashlib,subprocess,shutil,json
BASE=Path(sys.argv[1]) if len(sys.argv)>1 else Path('/mnt/data/L24H_v101121_GITHUB_DEPLOY_FOUR_PASS_REPORT_TOOLING_RECONCILIATION_R1_LOCKED.zip')
OUT=Path(sys.argv[2]) if len(sys.argv)>2 else Path('/tmp/l24h_v101122_rebuild')
EXPECTED='e22782a8dd73fb54287cd13d61b3ff217c4d24f33702bd1397dc1b4df5c34d3a'
VER='v101.122';STAGE='HOUR24_END_OF_CYCLE_STATE_AND_ACTION_HIERARCHY_R1';CACHE='luisa-24h-v101-122'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
if sha(BASE)!=EXPECTED: raise SystemExit(f'FAIL_BASELINE_IDENTITY {sha(BASE)}')
shutil.rmtree(OUT,ignore_errors=True);OUT.mkdir(parents=True)
with zipfile.ZipFile(BASE) as z:z.extractall(OUT)
patch=Path(__file__).with_name('patch_v101122_items.py')
for item in [f'H24-{i:02d}' for i in range(1,9)]: subprocess.run([sys.executable,str(patch),str(OUT),item],check=True,capture_output=True,text=True)
# mechanical identity changes not part of functional item patches
for htmlname in ['index.html','luisa_24_heures.html']:
 p=OUT/htmlname;s=p.read_text(encoding='utf-8')
 s=s.replace("const BUILD_DATE = '2026-08-25'; // v101.121 / four-pass report tooling reconciliation R1","const BUILD_DATE = '2026-08-25'; // v101.122 / Hour-24 end-of-cycle state and action hierarchy R1",1)
 p.write_text(s,encoding='utf-8')
sw=(OUT/'sw.js').read_text(encoding='utf-8').replace('/* v101.121 */','/* v101.122 */',1).replace("const CACHE_NAME = 'luisa-24h-v101-121';",f"const CACHE_NAME = '{CACHE}';",1);(OUT/'sw.js').write_text(sw,encoding='utf-8')
m=json.loads((OUT/'manifest.json').read_text());m['version']=VER;(OUT/'manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
v=json.loads((OUT/'version.json').read_text());v.update({'app_version':VER,'cache_name':CACHE,'release_scope':'Narrow reader/progress UX successor: restores Hour-24 Hour-level actions, separates cycle state from Hour state, gates completed-cycle restart to canonical 24/24 Méditée progress, removes the disabled Hour-24 next control, aligns progress terminology, and removes redundant in-content Home actions where persistent Accueil was verified. Corpus, speech/presentation data, topology, storage schema, highlighting and Help are unchanged.','real_device_status':'Physical Samsung/iPhone/iPad, installed-PWA, true offline cold reopen, VoiceOver/TalkBack and live GitHub Pages exact-byte binding NOT_TESTED for v101.122.','overall_release_status':'LIMITED_PASS_STATIC_IF_FINAL_REOPEN_AUDITS_PASS','known_blockers':[],'external_open_gates':['physical iPad/iPhone/Samsung','Hour-24 end-of-cycle real-device layout and live Méditée transition','live GitHub Pages exact-byte binding','installed PWA update','true offline cold reopen','VoiceOver/TalkBack representative testing']});(OUT/'version.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
readme=f'''# Les 24 Heures de la Passion — {VER}\n\nStage: `{STAGE}`\n\nImmutable baseline: v101.121 / `{EXPECTED}`.\n\nThis narrow successor changes the end-of-Hour/end-of-cycle reader UX and mechanically required release/evidence bindings only. Hour 24 now retains `Réflexion et pratique`, `Approfondir` and `Revenir au début`; cycle completion is driven by canonical `24/24` Méditée state rather than merely reaching Hour 24.\n\nProtected and unchanged from v101.121: canonical corpus text, the fourteen governed declarations, Help content, speech semantics, presentation projection/adjudications, display segmentation, Samsung paragraph topology, storage schema, notes/highlights and platform-specific highlighting models.\n\nPhysical-device/live-origin gates remain external and NOT_TESTED.\n'''
(OUT/'README.md').write_text(readme,encoding='utf-8')
# remove predecessor current reports/metadata/tooling that are regenerated by stage finalizer or are no longer current.
# Historical evidence directories remain untouched.
print(json.dumps({'status':'PASS_RUNTIME_REBUILD','baseline_sha256':EXPECTED,'version':VER,'stage':STAGE,'index_sha256':sha(OUT/'index.html'),'sw_sha256':sha(OUT/'sw.js'),'version_json_sha256':sha(OUT/'version.json')},indent=2))
