#!/usr/bin/env python3
import asyncio,json,sys
from pathlib import Path
from playwright.async_api import async_playwright
HTML=Path(sys.argv[1]).read_text(encoding='utf-8'); OUT=Path(sys.argv[2]);VER=sys.argv[3];STAGE=sys.argv[4]
P=[('phone',390,844,'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'),('ipad_p',820,1180,'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'),('ipad_l',1180,820,'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'),('desktop',1200,900,'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/142.0 Safari/537.36'),('samsung',412,915,'Mozilla/5.0 (Linux; Android 15; SM-S928B) AppleWebKit/537.36 Chrome/142.0 Mobile Safari/537.36 SamsungBrowser/28.0')]
async def main():
 rows=[]
 def add(p,n,ok,d=None):rows.append({'profile':p,'check':n,'status':'PASS' if ok else 'FAIL','detail':d})
 async with async_playwright() as pw:
  b=await pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
  for label,w,h,ua in P:
   c=await b.new_context(viewport={'width':w,'height':h},user_agent=ua);pg=await c.new_page();errs=[];pg.on('pageerror',lambda e:errs.append(str(e)));await pg.set_content(HTML,wait_until='domcontentloaded');await pg.wait_for_timeout(70)
   x=await pg.evaluate('''()=>({v:APP_VERSION,s:APP_EVIDENCE_STAGE,home:document.getElementById('content').innerText.length,bw:document.body.scrollWidth,iw:innerWidth,hours:CORPUS.hours.length,speech:Object.keys(SPEECH_DATA).length,proj:Object.keys(SPEECH_PRESENTATION_PROJECTION).length,adj:Object.keys(SPEECH_PRESENTATION_ADJUDICATIONS).length})''')
   add(label,'identity',x['v']==VER and x['s']==STAGE,x);add(label,'home_nonempty',x['home']>200,x['home']);add(label,'no_horizontal_overflow',x['bw']<=x['iw']+2,[x['bw'],x['iw']]);add(label,'24_hours',x['hours']==24,x['hours'])
   r=await pg.evaluate('''()=>{let bad=[];for(let n=1;n<=24;n++){try{openHour(n,false);let t=document.getElementById('content').innerText;if(t.length<1000)bad.push([n,t.length]);}catch(e){bad.push([n,String(e)])}}return bad}''');add(label,'render_24_hours',not r,r[:4])
   u=await pg.evaluate('''()=>{openHour(3,false);const h3=(document.getElementById('content').innerText.match(/Le monde des réprouvés est représenté par Judas/g)||[]).length;openHour(22,false);const ids=['PASSION24.HOUR.22.P048','PASSION24.HOUR.22.P050','PASSION24.HOUR.22.P052','PASSION24.HOUR.22.P054','PASSION24.HOUR.22.P056','PASSION24.HOUR.22.P059','PASSION24.HOUR.22.P061','PASSION24.HOUR.22.P063','PASSION24.HOUR.22.P065'];let ok=true;for(const id of ids){const e=document.getElementById(id),s=e?[...e.querySelectorAll('.para-seg')].map(x=>x.innerText):[];if(s.length!==2||!s[0].trimEnd().endsWith('».')||!s[1].startsWith('Jésus,')||getPresentationLocalBreaks(id).length!==1)ok=false}return{h3,ok,p70:document.getElementById('PASSION24.HOUR.22.P070').innerText,p71:document.getElementById('PASSION24.HOUR.22.P071').innerText}}''');add(label,'v101112_user_fixes',u['h3']==1 and u['ok'] and u['p70'].rstrip().endswith('».') and u['p71'].startswith('Jésus,'),u)
   q=await pg.evaluate('''()=>{showSearchView(false);performSearch('âme');return document.getElementById('homeSearchResults').querySelectorAll('.search-result-item').length}''');add(label,'search',q>0,q)
   me=await pg.evaluate('''()=>{showEspaceView(false);return document.getElementById('content').innerText.length}''');add(label,'mon_espace',me>100,me)
   # Direct controls central to this stage: P053/P068 visible, P090 complete JESUS presentation.
   ctrl=await pg.evaluate('''()=>{function inspect(pid,off){const t=getFullParaText(pid),d=document.createElement('div');d.innerHTML=renderParaText(t,pid);document.body.appendChild(d);let w=document.createTreeWalker(d,NodeFilter.SHOW_TEXT),n,b=0,o=null;while(n=w.nextNode()){if(off>=b&&off<b+n.nodeValue.length){let e=n.parentElement;o={ch:t[off],j:!!e.closest('.sp-jesus'),m:!!e.closest('.sp-mary'),f:!!e.closest('.sp-father'),h:!!e.closest('.speech-quote-hidden')};break}b+=n.nodeValue.length}d.remove();return o}return{p053:inspect('PASSION24.TEXT.RELATED_HOUR_06.BODY.P053',122),p068:inspect('PASSION24.TEXT.RELATED_HOUR_06.BODY.P068',312),p090o:inspect('PASSION24.TEXT.RELATED_HOUR_22.BODY.P090',215),p090c:inspect('PASSION24.TEXT.RELATED_HOUR_22.BODY.P090',238)}}''');ok=ctrl['p053']['ch']=='«' and ctrl['p053']['j'] and not ctrl['p053']['h'] and ctrl['p068']['ch']=='«' and ctrl['p068']['j'] and not ctrl['p068']['h'] and ctrl['p090o']['j'] and not ctrl['p090o']['h'] and ctrl['p090c']['j'] and not ctrl['p090c']['h'];add(label,'presentation_controls',ok,ctrl)
   add(label,'no_page_errors',not errs,errs);await c.close()
  await b.close()
 sm={'pass':sum(r['status']=='PASS' for r in rows),'fail':sum(r['status']=='FAIL' for r in rows),'total':len(rows)};OUT.write_text(json.dumps({'schema':'L24H_V101128_INDEPENDENT_RUNTIME_SMOKE_V1','version':VER,'summary':sm,'results':rows},ensure_ascii=False,indent=2)+'\n');print(json.dumps(sm));raise SystemExit(2 if sm['fail'] else 0)
asyncio.run(main())
