#!/usr/bin/env python3
import asyncio,json,sys
from pathlib import Path
from playwright.async_api import async_playwright
HTML=Path(sys.argv[1]).read_text(encoding='utf-8');OUT=Path(sys.argv[2]);VER='v101.132'
STUB="""() => { const mem=new Map(); const ls={getItem:k=>mem.has(String(k))?mem.get(String(k)):null,setItem:(k,v)=>mem.set(String(k),String(v)),removeItem:k=>mem.delete(String(k)),clear:()=>mem.clear(),key:i=>Array.from(mem.keys())[i]||null,get length(){return mem.size}}; Object.defineProperty(window,'localStorage',{value:ls,configurable:true}); }"""
async def main():
 rows=[]
 def add(case,ok,d=None):rows.append({'case':case,'status':'PASS' if ok else 'FAIL','detail':d})
 async with async_playwright() as pw:
  b=await pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage']);c=await b.new_context(viewport={'width':1200,'height':900});p=await c.new_page();await p.evaluate(STUB);errs=[];p.on('pageerror',lambda e:errs.append(str(e)));await p.set_content(HTML,wait_until='domcontentloaded');await p.wait_for_timeout(70)
  async def ev(code): return await p.evaluate(code)
  d=await ev("""()=>{state.readHours=new Set();openHour(23,false);const t=document.getElementById('content').innerText;return{actions:['Réflexion et pratique','Approfondir','Revenir au début','Prier la 24e Heure'].every(x=>t.includes(x)),progress:t.includes('Voir ma progression'),review:t.includes('Revoir les Heures méditées')}}""");add('S01_Hour23_unchanged',d['actions'] and not d['progress'] and not d['review'],d)
  d=await ev("""()=>{state.readHours=new Set();openHour(24,false);const x=document.getElementById('hour24CyclePanelHost').innerText;return{x}}""");add('S02_0of24','VOTRE PARCOURS' in d['x'] and '0/24' in d['x'] and 'Recommencer' not in d['x'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:22},(_,i)=>i+1));openHour(24,false);const x=document.getElementById('hour24CyclePanelHost').innerText;return{x}}""");add('S03_22of24','22/24' in d['x'] and 'Recommencer' not in d['x'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:23},(_,i)=>i+1));state.meditationLog=[];openHour(24,false);const before=document.getElementById('hour24CyclePanelHost').innerText;markMeditee(24);const after=document.getElementById('hour24CyclePanelHost').innerText;return{before,after,count:state.readHours.size,has24:state.readHours.has(24)}}""");add('S04_23_to_complete','23/24' in d['before'] and '24/24' in d['after'] and 'ACCOMPLI' in d['after'] and d['count']==24 and d['has24'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:24},(_,i)=>i+1));state.meditationLog=[];openHour(24,false);const before=document.getElementById('hour24CyclePanelHost').innerText;markMeditee(24);const after=document.getElementById('hour24CyclePanelHost').innerText;return{before,after,count:state.readHours.size,has24:state.readHours.has(24)}}""");add('S05_complete_to_23','24/24' in d['before'] and '23/24' in d['after'] and 'Recommencer' not in d['after'] and d['count']==23 and not d['has24'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:24},(_,i)=>i+1).filter(n=>n!==7));openHour(24,false);const x=document.getElementById('hour24CyclePanelHost').innerText;const p=getProgressSnapshot();return{x,p,has24:state.readHours.has(24)}}""");add('S06_H24_marked_other_missing',d['p']['count']==23 and d['has24'] and not d['p']['complete'] and 'Recommencer' not in d['x'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:24},(_,i)=>i+1));state.lastParas={24:'PASSION24.HOUR.24.P001'};state.hourTabs={24:'linked'};state.meditationLog=[{date:'2026-08-27',hour:24}];state.notes={n1:{text:'keep'}};state.textHighlights={x:[{id:'h',start_offset:0,end_offset:1,color:'yellow'}]};state.themePreference='dark';state.lastHour=24;const before=JSON.stringify(buildPersonalSnapshotFromState());window.confirm=()=>false;const ret=restartTwentyFourHours({requireComplete:true,destination:'hour1'});const after=JSON.stringify(buildPersonalSnapshotFromState());return{ret,same:before===after,count:state.readHours.size,lastHour:state.lastHour}}""");add('S07_restart_cancel',d['ret'] is False and d['same'] and d['count']==24 and d['lastHour']==24,d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:24},(_,i)=>i+1));state.lastParas={24:'PASSION24.HOUR.24.P001'};state.hourTabs={24:'linked'};state.meditationLog=[{date:'2026-08-27',hour:24}];state.notes={n1:{text:'keep'}};state.textHighlights={x:[{id:'h',start_offset:0,end_offset:1,color:'yellow'}]};state.libraryMarks={};state.themePreference='dark';state.lastHour=24;const before=JSON.stringify({notes:state.notes,textHighlights:state.textHighlights,libraryMarks:state.libraryMarks,themePreference:state.themePreference});window.confirm=()=>true;const ret=restartTwentyFourHours({requireComplete:true,destination:'hour1'});const after=JSON.stringify({notes:state.notes,textHighlights:state.textHighlights,libraryMarks:state.libraryMarks,themePreference:state.themePreference});return{ret,count:state.readHours.size,lastParas:Object.keys(state.lastParas).length,hourTabs:Object.keys(state.hourTabs).length,log:state.meditationLog.length,currentHour:state.currentHour,lastHour:state.lastHour,view:state.view,same:before===after}}""");add('S08_restart_confirm',d['ret'] and d['count']==0 and d['lastParas']==0 and d['hourTabs']==0 and d['log']==0 and d['currentHour']==1 and int(d['lastHour'])==1 and d['view']=='reader' and d['same'],d)
  d=await ev("""()=>{state.readHours=new Set(Array.from({length:23},(_,i)=>i+1));state.lastParas={24:'X'};state.notes={};const before=JSON.stringify(buildPersonalSnapshotFromState());window.confirm=()=>true;const ret=restartTwentyFourHours({requireComplete:true,destination:'hour1'});const after=JSON.stringify(buildPersonalSnapshotFromState());return{ret,same:before===after,count:state.readHours.size}}""");add('S09_forced_reset_incomplete_rejected',d['ret'] is False and d['same'] and d['count']==23,d)
  d=await ev("""()=>{openHour(24,false);goToHourTab('reflections','reflectionsContent');return{tab:state.activeTab,display:getComputedStyle(document.getElementById('reflectionsContent')).display}}""");add('S10_reflection_action',d['tab']=='reflections' and d['display']!='none',d)
  d=await ev("""()=>{openHour(24,false);goToHourTab('linked','linkedTextsContent');return{tab:state.activeTab,display:getComputedStyle(document.getElementById('linkedTextsContent')).display}}""");add('S11_linked_action',d['tab']=='linked' and d['display']!='none',d);await p.wait_for_timeout(120)
  await ev("""()=>{if(_stage6aSaveTimer)clearTimeout(_stage6aSaveTimer);if(_stage6aRestoreTimer)clearTimeout(_stage6aRestoreTimer);_stage6aSaveTimer=null;_stage6aRestoreTimer=null;_stage6aLastAnchor=null;suppressScrollSaveUntil=Date.now()+1200;state.lastParas={};openHour(24,false);const c=document.getElementById('content');c.scrollTop=Math.max(300,c.scrollHeight-400);scrollReaderToTop()}""");await p.wait_for_timeout(120);d=await ev("""()=>({hour:state.currentHour,view:state.view,scroll:document.getElementById('content').scrollTop})""");add('S12_return_to_top',d['hour']==24 and d['view']=='reader' and d['scroll']<=5,d)
  d=await ev("""()=>{showProgressView(false);const home=[...document.querySelectorAll('.bottom-nav button')].find(x=>/Accueil/.test(x.innerText||x.getAttribute('aria-label')||''));if(home)home.click();return{home:!!home,view:state.view}}""");add('S13_progress_home',d['home'] and d['view']=='home',d)
  d=await ev("""()=>{showCompletedHoursView(false);const home=[...document.querySelectorAll('.bottom-nav button')].find(x=>/Accueil/.test(x.innerText||x.getAttribute('aria-label')||''));if(home)home.click();return{home:!!home,view:state.view}}""");add('S14_completed_home',d['home'] and d['view']=='home',d)
  d=await ev("""()=>{localStorage.clear();state.readHours=new Set();state.meditationLog=[];openHour(6,false);markMeditee(6);const raw=localStorage.getItem(PERSONAL_SNAPSHOT_KEY);state.readHours=new Set();state.meditationLog=[];loadState();return{raw:!!raw,has6:state.readHours.has(6),count:state.readHours.size,log:state.meditationLog.some(x=>x.hour===6)}}""");add('S15_meditee_persists',d['raw'] and d['has6'] and d['count']==1 and d['log'],d)
  d=await ev("""()=>{localStorage.clear();state.readHours=new Set(Array.from({length:24},(_,i)=>i+1));state.lastParas={24:'X'};state.hourTabs={24:'linked'};state.meditationLog=[{date:'2026-08-27',hour:24}];state.lastHour=24;window.confirm=()=>true;const ret=restartTwentyFourHours({requireComplete:true,destination:'hour1'});const raw=localStorage.getItem(PERSONAL_SNAPSHOT_KEY);const snap=raw?JSON.parse(raw):null;state.readHours=new Set([2]);state.lastHour=2;loadState();return{ret,raw:!!raw,snapRead:snap&&snap.readHours,snapLast:snap&&snap.lastHour,loadedCount:state.readHours.size,loadedLast:state.lastHour}}""");add('S16_reset_persists',d['ret'] and d['raw'] and d['snapRead']==[] and str(d['snapLast'])=='1' and d['loadedCount']==0 and int(d['loadedLast'])==1,d)
  add('NO_PAGE_ERRORS',not errs,errs)
  await c.close();await b.close()
 summary={'pass':sum(r['status']=='PASS' for r in rows),'fail':sum(r['status']=='FAIL' for r in rows),'total':len(rows)};OUT.write_text(json.dumps({'schema':'L24H_V101128_HOUR24_REGRESSION_MATRIX_V1','version':VER,'summary':summary,'rows':rows},ensure_ascii=False,indent=2)+'\n');print(json.dumps(summary));
 if summary['fail']:
  for r in rows:
   if r['status']=='FAIL':print('FAIL',r)
  raise SystemExit(2)
asyncio.run(main())
